# Compiler-specific definitions: Watcom C++ building Windows NT executables

#########################################################################
# additional location setups required by Watcom's difference commandline
# parsing

# where to put the compiled library and required header files
INSTDIR = $(TOP)\include
LIBINSTDIR = $(TOP)\lib
# where to look for header files from other modules when compiling
INCLUDEDIRS = -i=$(TOP)\include
# where to look for library files when linking
LIBDIR = $(TOP)\lib

#########################################################################
# define the compiler and its options

DBGLVL=1 	     	# debugging: 0=none, 1=lines only, 2=full
CPU=6			# target CPU: (3)86, (4)86, (5)86, (6)86 [v11.0+]
#PROFILE=-et		# Pentium+ only: emit profiling code
#OPTFLAGS=-onatxle=2	# Watcom 10.x
OPTFLAGS=-onatxhe=0	# Watcom 11.0 (-ox now also implies -ol; -oh is new)
			#  (compiler crashes with e=<nonzero>, so either don't
			#   limit inlining of user funcs or omit "e=0")
CC = wpp386
CCLINK = wcl386
CFLAGS = -zq $(OPTFLAGS) -fp$(CPU) -$(CPU)r -wx -mf -d$(DBGLVL) -bt=NT -zw -bc $(PROFILE)
CFLAGEXE = -l=nt -d$(DBGLVL) $(PROFILE)
LINKFLAGS =

# CFLAGS above:
#   -bc   console app
#   -bw   windowed app

#########################################################################
# define the object module librarian and its options

LIBRARIAN = wlib
LIBFLAGS = -q -c -p=32
LIBOBJS = @objs.lst
# (objs.lst contains a list of all the object modules in $(OBJS) )

#########################################################################
# define the library indexer and its options

LIBINDEXER = @echo
LIBIDXFLAGS = library built

#########################################################################
# define file copy/deletion/etc. programs

# (note: makefile assumes 4DOS or other progs handling multiple files)
RM = del
CP = copy
ZIP = pkzip
ZIPFLAGS = -o -ex
BITBUCKET = >NUL
TOUCH = touch

#########################################################################
# define the various extensions in use

OBJ = .obj
EXE = .exe
LIB = .lib
C = .cpp

#########################################################################
# define the required libraries in the proper format for the compiler/OS

USELIBS = $(LIBDIR)\ebmt$(LIB) $(LIBDIR)\framepac$(LIB)

#########################################################################
# define the default compile rule

$(C)$(OBJ):
       $(CC) $* $(CFLAGS) $(INCLUDEDIRS)

#########################################################################

# End of Makefile
